"""Main entry point for FiveM Script Generator."""

import io
import os
import sys
from datetime import datetime
from pathlib import Path

# Fix Windows encoding issues
if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

from dotenv import load_dotenv

load_dotenv()

from src.crew import FiveMScriptCrew
from src.config.settings import get_settings
from src.models.schemas import GeneratedCode


def save_lua_files(generated_code: GeneratedCode, output_dir: str) -> Path:
    """Save generated Lua files to disk.
    
    Args:
        generated_code: The generated code from the crew
        output_dir: Base output directory
        
    Returns:
        Path: Path to the created resource folder
    """
    resource_path = Path(output_dir) / generated_code.resource_name
    resource_path.mkdir(parents=True, exist_ok=True)
    
    files_to_save = {
        "client.lua": generated_code.client_lua,
        "server.lua": generated_code.server_lua,
        "config.lua": generated_code.config_lua,
        "fxmanifest.lua": generated_code.fxmanifest_lua,
    }
    
    for filename, content in files_to_save.items():
        file_path = resource_path / filename
        file_path.write_text(content, encoding="utf-8")
        print(f"✅ Saved: {file_path}")
    
    for additional_file in generated_code.additional_files:
        file_path = resource_path / additional_file.filename
        file_path.write_text(additional_file.content, encoding="utf-8")
        print(f"✅ Saved: {file_path}")
    
    if generated_code.installation_notes:
        readme_path = resource_path / "README.md"
        readme_content = f"""# {generated_code.resource_name}

## Framework
{generated_code.framework.value.upper()}

## Installation
{generated_code.installation_notes}

## Files
- `client.lua` - Client-side logic
- `server.lua` - Server-side logic
- `config.lua` - Configuration options
- `fxmanifest.lua` - Resource manifest

## Generated by
FiveM CrewAI Generator
"""
        readme_path.write_text(readme_content, encoding="utf-8")
        print(f"✅ Saved: {readme_path}")
    
    return resource_path


class TeeOutput:
    """Tee output to both console and log file."""
    
    def __init__(self, log_file: Path):
        self.terminal = sys.stdout
        self.log_file = log_file
        self.log_buffer = io.StringIO()
    
    def write(self, message: str):
        self.terminal.write(message)
        self.log_buffer.write(message)
    
    def flush(self):
        self.terminal.flush()
    
    def save_log(self):
        with open(self.log_file, "a", encoding="utf-8") as f:
            f.write(f"\n{'='*60}\n")
            f.write(f"Generation at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"{'='*60}\n")
            f.write(self.log_buffer.getvalue())


def main() -> None:
    """Main entry point."""
    settings = get_settings()
    
    log_file = Path("generation.log")
    tee = TeeOutput(log_file)
    sys.stdout = tee
    
    print("=" * 60)
    print("🎮 FiveM Script Generator - Powered by CrewAI")
    print("=" * 60)
    print()
    
    if len(sys.argv) > 1:
        user_requirement = " ".join(sys.argv[1:])
    else:
        print("📝 Enter your FiveM script requirement:")
        print("   (Describe what you want: script type, features, framework)")
        print()
        user_requirement = input("Requirement: ").strip()
    
    if not user_requirement:
        print("❌ Error: No requirement provided")
        sys.exit(1)
    
    print()
    print(f"📋 Requirement: {user_requirement}")
    print()
    print("🚀 Starting script generation...")
    print("=" * 60)
    print()
    
    crew = FiveMScriptCrew(user_requirement)
    generated_code = crew.run()
    
    print()
    print("=" * 60)
    print("💾 Saving generated files...")
    print("=" * 60)
    print()
    
    output_path = save_lua_files(generated_code, settings.output_dir)
    
    print()
    print("=" * 60)
    print("✨ Generation Complete!")
    print("=" * 60)
    print()
    print(f"📁 Resource created: {output_path}")
    print(f"🎯 Framework: {generated_code.framework.value.upper()}")
    print()
    print("📄 Generated files:")
    print(f"   - {output_path}/client.lua")
    print(f"   - {output_path}/server.lua")
    print(f"   - {output_path}/config.lua")
    print(f"   - {output_path}/fxmanifest.lua")
    
    if generated_code.additional_files:
        for f in generated_code.additional_files:
            print(f"   - {output_path}/{f.filename}")
    
    print()
    print("🎮 Copy this folder to your FiveM server's resources directory")
    print("   and add 'ensure " + generated_code.resource_name + "' to server.cfg")
    print()
    print("🌐 View output: python server.py → http://localhost:8080")
    print()
    
    tee.save_log()
    sys.stdout = tee.terminal


if __name__ == "__main__":
    main()
